from __future__ import unicode_literals

DJANGO_SETTINGS_DEFAULTS = {
    # Default in YAML format
    'DEBUG': 'false',
    'LOGIN_URL': 'authentication:login_view',
    'LOGIN_REDIRECT_URL': 'common:home',
    'LOGOUT_REDIRECT_URL': 'authentication:login_view',
}


DJANGO_SETTINGS_LIST = (
    'ALLOWED_HOSTS', 'APPEND_SLASH', 'AUTH_PASSWORD_VALIDATORS',
    'DATA_UPLOAD_MAX_MEMORY_SIZE', 'DATABASES', 'DEBUG', 'DEFAULT_FROM_EMAIL',
    'DISALLOWED_USER_AGENTS', 'EMAIL_BACKEND', 'EMAIL_HOST',
    'EMAIL_HOST_PASSWORD', 'EMAIL_HOST_USER', 'EMAIL_PORT', 'EMAIL_TIMEOUT',
    'EMAIL_USE_SSL', 'EMAIL_USE_TLS', 'FILE_UPLOAD_MAX_MEMORY_SIZE',
    'HOME_VIEW', 'INSTALLED_APPS', 'INTERNAL_IPS', 'LANGUAGES',
    'LANGUAGE_CODE', 'LOGIN_REDIRECT_URL', 'LOGIN_URL', 'LOGOUT_REDIRECT_URL',
    'STATIC_URL', 'STATICFILES_STORAGE', 'TIME_ZONE', 'WSGI_APPLICATION'
)
